[package]
name = "aes_gcm_stream_wasm"
version = "0.1.0"
edition = "2024"

[lib]
# produce a CDyLib for wasm-pack
crate-type = ["cdylib"]

[dependencies]
# Streaming AES-GCM implementation (patched below)
aes-gcm-stream = "0.2.4"
# Interface between Wasm and JS
wasm-bindgen = "=0.2.101"

[patch.crates-io]
aes-gcm-stream = { path = "./patches/aes-gcm-stream" }

[dev-dependencies]
wasm-bindgen-test = "=0.3.51"