#!/usr/bin/env node
/**
 * Generate `src/embedded-wasm-base64.ts` from the built wasm binary.
 *
 * Runs as part of `pnpm build` (after `build:rust`, before `tsc`). The output
 * is git-ignored, like the `.wasm` binary it is derived from, so the embedded
 * bytes can never drift from the compiled module.
 *
 * Raw base64 rather than gzip+base64: HTTP transfer compression already shrinks
 * the base64 text to roughly the gzip size of the binary, and it avoids a
 * runtime dependency on `DecompressionStream` (Safari < 16.4).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const wasmPath = path.join(root, 'wasm/aes_gcm_stream_wasm_bg.wasm');
const outputPath = path.join(root, 'src/embedded-wasm-base64.ts');

const wasm = readFileSync(wasmPath);
const base64 = wasm.toString('base64');

writeFileSync(
  outputPath,
  `// Generated by scripts/embed-wasm.mjs from wasm/aes_gcm_stream_wasm_bg.wasm. Do not edit.\n` +
    `/** The compiled wasm module, base64-encoded. */\n` +
    `export const EMBEDDED_WASM_BASE64 =\n  ${JSON.stringify(base64)};\n`,
);

console.log(
  `Wrote src/embedded-wasm-base64.ts (${String(wasm.length)} wasm bytes, ${String(base64.length)} base64 chars)`,
);
